services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: timescaledb
      REDIS_HOST: redis
    depends_on:
      - timescaledb
      - redis
